# Generated by Django 5.1.2 on 2025-04-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_bookingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='shop',
        ),
    ]
