# Generated by Django 5.1.2 on 2025-04-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customerprofile_remember_me'),
        ('order', '0006_booking_price_booking_shop_cartitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.shopprofile'),
        ),
    ]
