# Generated by Django 5.1.2 on 2025-04-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderrequest_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.CharField(blank=True, choices=[('cop', 'Cash on Payment'), ('online', 'Online Payment')], max_length=10, null=True),
        ),
    ]
