# Generated by Django 5.1.2 on 2025-05-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_booking_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
